# Generated by Django 5.2.1 on 2025-05-16 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('order_token', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('buyer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('buyer_phone', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('recipient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('shipping_address', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('card', 'Credit Card'), ('bank', 'Bank Transfer')], max_length=20)),
                ('cash_receipt_type', models.CharField(choices=[('personal', 'Personal'), ('business', 'Business'), ('none', 'None')], default='none', max_length=20)),
                ('cash_receipt_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productoption')),
            ],
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('session_id__isnull', False), _connector='OR'), name='order_user_or_session_required'),
        ),
    ]
